.PHONY: all clean

all:
	@cd hw1 && make all
	@cd hw2 && make all
	@cd hw3 && make all
	@cd hw5 && make all
	@cd exam-midterm && make all
	@cd exam-final && make all

clean:
	@cd hw1 && make clean
	@cd hw2 && make clean
	@cd hw3 && make clean
	@cd hw5 && make clean
	@cd exam-midterm && make clean
	@cd exam-final && make clean
