.PHONY: all clean

all:
	@cd hw2 && make all
	@cd hw4 && make all
	@cd hw6 && make all
	@cd hw7 && make all
	@cd exam-midterm && make all

clean:
	@cd hw2 && make clean
	@cd hw4 && make clean
	@cd hw6 && make clean
	@cd hw7 && make clean
	@cd exam-midterm && make clean
